application:
  port: 4000
  hmac_secret: "long-and-cool-secret-that-is-even-longer-than-before-thats-over-64-bytes"
redis_uri: "redis://127.0.0.1:6379"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "127.0.0.1"
  sender_email: "test@gmail.com"
  authorization_token: "mamajamba123"
  timeout_milliseconds: 10000
